### ISSUE TITLE
How is 'Local Path' working?

### ISSUE THREAD

**Issue by guwirth** [etas/SonarLink#10]
Don't understand how this  'Local Path' setting is working. Could you explain it in the documentation please?

**Comment by netspiri** [comment]
'Local Path' setting is documented in the following wiki page: https://github.com/etas/SonarLink/wiki/SonarLink.

**Comment by guwirth** [comment]
@netspiri if you click the link https://github.com/etas/SonarLink/wiki the starting pages looks empty. Mabe better to move it to starting page?
