### ISSUE TITLE
Handle projects with 10K+ issues

### ISSUE THREAD

**Issue by guwirth** [etas/SonarLink#11]
At the moment there is a limit of 10k issues per project.

As an user I like to download an see all issues of a project.

**Comment by netspiri** [comment]
This issue has already been handled in the base version.

Issues are split based on error category and multiple requests are issued to the Sonar server. This avoids the 10K limit imposed by Sonar. The results are then aggregated as 1 list. Note that there might still be scenarios where not all issues are listed should 10K+ issues be categorized under the same error type.
