### ISSUE TITLE
Handle no responses from SonarQube server

### ISSUE THREAD

**Issue by guwirth** [etas/SonarLink#13]
Gracefully handle no responses from SonarQube server. Plugin currently hangs UI.

As an user I like to get a meaningful error message if the plugin is not able to connect to SonarQube server.

**Comment by netspiri** [comment]
Base version tries to handle errors as 'gracefully' as possible, notifying errors to the user through notifications within the 'Team Explorer' pane. Plugin remains responsive throughout error conditions.

Closing issue. Should any such similar issues occur in the future, an issue should be raised for a specific cause.
