### ISSUE TITLE
Communication with SonarQube server should be asynchronous

### ISSUE THREAD

**Issue by guwirth** [etas/SonarLink#14]
Asynchronisation of the plugin as a whole. Getting projects, viewing issues, setting local path commands currently hang the UI while completing.

Plugin should not block UI during SonarQube server communication.

**Comment by netspiri** [comment]
The base version is developed in such a way to make the best use of `async`/`await`. Ad-hoc tests show that the plugin remains responsive when Sonar communication is underway.
