### ISSUE TITLE
Setup AppVeyor CI

### ISSUE THREAD

**Issue by guwirth** [etas/SonarLink#16]
Setup an CI with AppVeyor:
* build new binaries/packages
* ensure unique versioning
* run tests
* run TechnicalDebt analysis => use SonarCloud
* provide installation
* should work with main branch and Pull Requests

**Comment by netspiri** [comment]
AppVeyor CI is possible to setup by linking the repository to AppVeyor (e.g. https://ci.appveyor.com/project/netspiri/sonarlink).

All that is left is to configure and integrate with SonarCloud.

**Comment by guwirth** [comment]
@netspiri problem is that there is debug and release. I know no way to create a link to artifacts? If in master is only release you can create a link (without job id).

|     |     |     |
| --- | --- | --- |
| **AppVeyor CI**| [![Build status](https://ci.appveyor.com/api/projects/status/github/etas/SonarLink?svg=true)](https://ci.appveyor.com/project/netspiri/sonarlink/branch/master) | [Download latest snapshot](https://ci.appveyor.com/project/netspiri/sonarlink/branch/master/artifacts) |
