### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by guwirth** [etas/SonarLink#2]
An user should be able to use the SonarLink extension with Visual Studio 2019.

**Comment by netspiri** [comment]
Experimental support for SonarLink in Visual Studio 2019 is available. Experimental installer is available via CI (e.g. https://ci.appveyor.com/project/netspiri/sonarlink/build/job/mlgaq1rwwhobnvh2/artifacts).

Future work might require updating the VSIX project structure to be able to deliver both Visual Studio 2017 and Visual Studio 2019 extensions in the same VSIX package. This should avoid the package split and should allow for only 1 Visual Studio Marketplace item.
