### ISSUE TITLE
Filter issues by type

### ISSUE THREAD

**Issue by guwirth** [etas/SonarLink#6]
As an user I like to filter the issue list by type:
- Bug
- Vulnerability
- Code Smell

Hint: If "filter" is not possible another solution could be to select which issues should be downloaded.

**Comment by netspiri** [comment]
Should already be possible as of base version. If the 'Category' column is not available, right-click on an existing column in the 'Error List' pane and select the appropriate column from the 'Show Columns' option. The 'Filter' icon should appear once you hover the mouse over the column of interest.

![image](https://user-images.githubusercontent.com/6962427/62360968-4d2bbd00-b51a-11e9-9f7f-44ecc970570d.png)
