### ISSUE TITLE
Show category of issues

### ISSUE THREAD

**Issue by guwirth** [etas/SonarLink#8]
At the moment all issues are mapped to Info in the Error List. Should be differentiated between Error, Warning and Info:

* Error List / `Error`:
  * SQ Type: `Bug `or `Vulnerability`
  * SQ Severity: all except Info
* Error List / `Warning`:
  * SQ Type: `Code Smell`
  * SQ Severity:  all except Info
* Error List / `Info`:
  * SQ Type: ---
  * SQ Severity: `Info`

As an user I like to see the issue category more differentiated in the Visual Studio Error List.

**Comment by netspiri** [comment]
Future work. This should be a relatively simple matter of adapting the `Severity` property of `ErrorListItem` based on the noted specifications.
